version: '3.4'

services:
  droproot:
    image: droproot
    deploy:
      replicas: 2
    ports:
      - '8443:8443'
    configs:
      - source: collector_address
        target: /glowroot.properties.sample
configs:
  collector_address:
    file: ./glowroot.properties
