version: "3.4"

services:
  droproot:
    image: droproot
    deploy:
      replicas: 2
    environment:
      COLLECTOR_ADDRESS: "10.0.0.10:8181"
    ports:
      - "8443:8443"
      # - "8444:8444"
    healthcheck:
      test: "curl --fail http://localhost:8081/healthcheck || exit 1"
      interval: 1m
      timeout: 1s
      retries: 3
      start_period: 30s