version: "3.4"

services:
  cassandra:
    image: cassandra
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5

  glowroot:
    image: glowroot/glowroot-central:0.13.1
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:4000/", "||", "exit 1"]
      interval: 1m
      timeout: 3s
      retries: 3
      start_period: 15s
    ports:
      - "4000:4000"
      - "8181:8181"

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]